name: App build

on:
  push:
    branches:
      - "1.0rc0"

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  windows-build:
    name: Windows Build

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pareto-ui-env
      
      - name: Install Azure Signtool
        run: |
          dotnet tool install --global AzureSignTool

      - name: Add project pareto version to .env file
        working-directory: ./electron/ui
        run: |
            echo REACT_APP_PARETO_VERSION=1.0.0rc1 >> .env

      - name: Install Electron JS dependencies
        run: |
          npm --prefix electron clean-install
      - name: Install frontend JS dependencies
        run: |
          npm --prefix electron/ui clean-install
      - name: Get idaes extensions
        run: idaes get-extensions

      # - name: Install Pareto locally
      #   working-directory: ../
      #   run: git clone https://github.com/MichaelPesce/project-pareto.git && cd project-pareto && pip install --progress-bar off .

      - name: Install correct tag of pareto
        working-directory: ../
        run: git clone https://github.com/project-pareto/project-pareto.git && cd project-pareto && git fetch --all --tags && git checkout tags/1.0.0rc1 -b 1.0.0rc1 && pip install --progress-bar off .

      - name: Install numpy 1.24.3
        run: |
          pip uninstall -y numpy && pip install numpy==1.24.3

      - name: Build Backend
        run: npm --prefix electron run build-backend

      - name: Build Frontend
        run: npm --prefix electron run build-frontend-win

      - name: Build Windows Distribution
        run: npm --prefix electron run electron-build-win

      - name: Sign Windows Distribution
        run: |
          AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v electron/dist/ParetoUI-24.06.28-win64.exe

      - name: Upload artifact for windows build
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: windows-pareto-dist
            path: |
              electron/dist/ParetoUI-24.06.28-win64.exe